import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/app/_components/Navbar";
import Footer from "@/app/_components/Footer";

const marriWeather = localFont({
  src: "./fonts/Merriweather-Regular.ttf",
  display: "swap",
});

export const metadata = {
  title: "Online Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${marriWeather.className} antialiased min-h-svh flex flex-col`}
      >
        <Navbar />
        <main className="flex-1 bg-primary-dark text-slate-100">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
